"""add project glyph color

Revision ID: fd4bb0e7766f
Revises: 4b3ea60ab673
Create Date: 2026-06-19 02:23:03.573366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4bb0e7766f'
down_revision: Union[str, None] = '4b3ea60ab673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('glyph', sa.String(length=8), nullable=True))
    op.add_column('project', sa.Column('color', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'color')
    op.drop_column('project', 'glyph')
    # ### end Alembic commands ###
